language: node_js
node_js:
  - "10.15.1"
cache:
  yarn: true
  directories:
  - node_modules
install:
  - npm install -g @shopify/slate-tools --unsafe-perm=true --allow-root
  - npm install -g stylelint
  - npm install
  - echo -e "SLATE_PASSWORD=${APP_PASSWORD}\nSLATE_THEME_ID=${SP}${APP_THEME_ID}\nSLATE_STORE=${APP_STORE}\nSLATE_USER_EMAIL=viktor@bystrov.agency\n" > ./.env
script:
  - yarn lint --styles --verbose
after_success: yarn deploy
notifications:
  email: false
  slack:
    on_success: change
    on_pull_requests: false
    template:
    - "%{repository_slug} (%{commit}) : %{message}"
    - 'Build details: %{build_url}'
    rooms:
      secure: GviD9jrtrkpmtWIp4zBGMLGDndC/lfm5kd/YM5qrUzN4Vm7V/oLr8elpE69sPhpKQKPrG1Veyr4SoXrRLTP1Vxgh6R+1dEt+1GyJdQlB8+AEVr5yKSOLMrflY3jGC+IKf6CTZgzSc6Ohbj4Li/FqBaSDxmIkb0/Vy448id1KpaEsQoXFryOOYXKb2RPnde8zTtgVZnp75dUbV3seycfZlg/kzYdyRTQ+nYumjmtuid6OrTP/V4+pu2PEMUtmO7iCe5kaPpmTNBr0wJGv2zS251OfpEMN/pBXfkHP1gASyIrbHjFw3MNZN548EFCVX2XVqAWwB72RpmGB5Wh/ljhzfcL3U4NwYA0gaZAs9orDgcIxITKQqQI0BYKQnDa5OJY7GFUbtFyk3O1oRZJbyw6whj6I8n48H/9Et2Y/H1TY5nWjvIN+/Ssy8R+BsVRYlJxSO0metK+qONJFC3yyioHXm+JEHEHFhaI3DhWRVLqgZ7NGzZQcRdZRXDvCCaz8W4Ghj8SdQYrS3FeQWAYPYWQTdYrcSxwwjE+/DpH7hHt9aRW82HhhJsA+men2ACQp/VQHbAIVh1GquoAvmRsKgFwZ/6WMiVECJPWRTgKMRCWHSDAvLjOA/lkk8wYD/yF1HvgwYLVo25plnT0PDbWfqgksmen7hoHFl4tPKX1/REyaqXA=
